[package]
name = "src"
version = "0.1.0"
authors = ["wrbe9001"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = "0.24.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"