#!/bin/sh

. ./common.sh

ensure_env CURRENT_VERSION

printf "Running 'Load' for $REPO:$CURRENT_VERSION\n"

TMP_DIR=/tmp/checkout

git clone $REPO $TMP_DIR

cd $TMP_DIR

git checkout $CURRENT_VERSION

if [[ "$CHECKOUT_DIR" == "" ]]; then
    mv $TMP_DIR/* /output
else
    mkdir -p /output/$CHECKOUT_DIR
    mv $TMP_DIR/* /output/$CHECKOUT_DIR
fi