#!/bin/sh

. ./common.sh

ensure_env

TMP_DIR=/tmp/checkout
mkdir -p $TMP_DIR

git clone $REPO $TMP_DIR

cd $TMP_DIR
git checkout $BRANCH || git checkout -b $BRANCH

cp /input/* $TMP_DIR

git add .
git commit -m "updated by git-resource"
git push -u origin $BRANCH