#!/bin/sh

. ./common.sh

ensure_env COMMIT_MESSAGE

TMP_DIR=/tmp/checkout
mkdir -p $TMP_DIR

git clone $REPO $TMP_DIR

cd $TMP_DIR
git checkout $BRANCH || git checkout -b $BRANCH

cp /input/* $TMP_DIR

git add .
git commit -m "$COMMIT_MESSAGE"
git push -u origin $BRANCH
