apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: version-sidecar
rules:
- apiGroups: ["minion.ponglehub.com"]
  resources: ["versions"]
  verbs: ["create", "delete", "get", "list"]