apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: task-reader
rules:
- apiGroups: ["minion.ponglehub.com"] # "" indicates the core API group
  resources: ["tasks"]
  verbs: ["get", "watch", "list"]