#!/bin/bash

docker run \
    --rm -it \
    -w /var/apps/src \
    -v $(pwd):/var/apps/src \
    -v cargo_cache:/usr/local/cargo/registry \
    -e USER=$USER \
    -e RUST_BACKTRACE=1 \
    rust cargo $@