apiVersion: v2
name: Minion-Operators
description: A Helm chart for the Minion CI system

type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
 - name: pipeline-monitor
   version: ~0.1.0
   repository: file://../../components/operators/pipeline-monitor/chart
 - name: task-monitor
   version: ~0.1.0
   repository: file://../../components/operators/task-monitor/chart
 - name: version-monitor
   version: ~0.1.0
   repository: file://../../components/operators/version-monitor/chart
 - name: git-resource
   version: ~0.1.0
   repository: file://../../components/resources/git-resource/chart