{{- if .Values.test.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-repo-deployment
  labels:
    app: git-repo
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/gogs.config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-repo
  template:
    metadata:
      labels:
        app: git-repo
    spec:
      containers:
      - name: git-repo
        image: {{ .Values.git.image }}
        {{ include "resources" .Values.git.resources | indent 8 | trim }}
        volumeMounts:
        - name: config
          mountPath: /data/gogs/conf
      volumes:
      - name: config
        configMap:
          name: gogs-config
          items:
          - key: app.ini
            path: app.ini
{{- end -}}