{{- if .Values.test.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: git-resource-test
rules:
- apiGroups: ["", "batch"]
  resources: ["services", "jobs"]
  verbs: ["create", "delete", "get"]
{{- end -}}