{{- if .Values.test.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "git-resource-test-{{ .Release.Revision }}"
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccount: git-resource-test
      containers:
      - name: test
        image: {{ .Values.test.image }}
        envFrom:
        - configMapRef:
            name: test-env
        command: ["npm", "test"]
        {{ include "resources" .Values.test.resources | indent 8 | trim }}
      restartPolicy: Never

{{- end -}}