{{- if .Values.test.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "git-resource-test-{{ .Release.Revision }}"
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccount: git-resource-test
      containers:
      - name: test
        image: {{ .Values.test.image }}
        env:
        - name: TEST_NAMESPACE
          value: "git-resource-test-{{ .Release.Revision }}"
        - name: PARENT_REPO
          value: {{ .Values.test.parentRepo }}
        - name: TEST_REPO
          value: {{ .Values.test.repo }}
        - name: TEST_BRANCH
          value: {{ .Values.test.branch }}
        - name: GIT_RESOURCE_IMAGE
          value: {{ .Values.image }}
        - name: FILE_INSPECTOR_IMAGE
          value: {{ .Values.test.sidecar }}
        command: ["npm", "test"]
        {{ include "resources" .Values.test.resources | indent 8 | trim }}
      restartPolicy: Never

{{- end -}}