apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-monitor-deployment
  labels:
    app: task-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-monitor
  template:
    metadata:
      labels:
        app: task-monitor
    spec:
      serviceAccount: task-reader
      containers:
      - name: task-monitor
        image: {{ .Values.image }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}