apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.minion.ponglehub.com
spec:
  group: minion.ponglehub.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resources:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      trigger:
                        type: boolean
                      secrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            keys:
                              type: array
                              items:
                                type: object
                                properties:
                                  key:
                                    type: string
                                  path:
                                    type: string
                      env:
                        type: object
                steps:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      resource:
                        type: string
                      action:
                        type: string
                        enum: [ GET, POST ]
                      path:
                        type: string
                      image:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                    oneOf:
                      - required: [ resource, action, path ]
                      - required: [ image, command ]
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
    - pi