apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources.minion.ponglehub.com
spec:
  group: minion.ponglehub.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                additionalVars:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: resources
    singular: resource
    kind: Resource
    shortNames:
    - res