apiVersion: batch/v1
kind: Job
metadata:
  name: "file-inspector-test-{{ .Release.Revision }}"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: test
        image: {{ .Values.test.image }}
        env:
        - name: TARGET_URL
          value: http://file-inspector
        - name: TARGET_PORT
          value: "80"
        - name: TARGET_DIR
          value: /data
      restartPolicy: Never