{{- range .Values.modules }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .name }}-{{ $.Release.Revision }}"
spec:
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: install
        image: {{ .image }}
        imagePullPolicy: Always
        args: [ install ]
        volumeMounts:
        - name: node-modules
          mountPath: /var/app/src/node_modules
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpu }}
            memory: {{ $.Values.resources.limits.memory }}
      - name: unit-test
        image: {{ .image }}
        imagePullPolicy: Always
        args: [ run, test ]
        volumeMounts:
        - name: node-modules
          mountPath: /var/app/src/node_modules
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpu }}
            memory: {{ $.Values.resources.limits.memory }}
      containers:
      - name: publish
        image: {{ .image }}
        imagePullPolicy: Always
        args: [ publish ]
        volumeMounts:
        - name: node-modules
          mountPath: /var/app/src/node_modules
        resources:
          limits:
            cpu: {{ $.Values.resources.limits.cpu }}
            memory: {{ $.Values.resources.limits.memory }}
      restartPolicy: Never
      volumes:
      - name: node-modules
        emptyDir: {}
{{- end }}